server:
  port: 8080

spring:
  application:
    name: order-service

  r2dbc:
    url: r2dbc:postgresql://orders_postgres:5432/orders_db
    username: orders_user
    password: orders_pass
    properties:
      schema: public

  flyway:
    enabled: false # si luego quieres migraciones, lo activamos

  data:
    mongodb:
      uri: mongodb://orders_mongo:27017/orders_events

  kafka:
    bootstrap-servers: orders_kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Swagger UI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
